name: 🤕 Hotfix Start
on:
  workflow_dispatch:
permissions:
  contents: write
run-name: 🤕 hotfix-start
jobs:
  hotfix:
    runs-on: ubuntu-latest
    steps:
      - name: ✅ Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ github.token }}
          fetch-depth: 0
      - uses: ./.github/actions/hotfix_start
        with:
          token: ${{ github.token }}
